services:
  db:
    image: postgres:latest
    container_name: nutrition-checker-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: justin
      POSTGRES_DB: nutrition_checker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
